apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: tamper-container-dns-by-id
spec:
  experiments:
    - scope: container
      target: network
      action: dns
      desc: "tamper container dns by id"
      matchers:
        - name: container-names
          value:
            - "productpage"
        - name: domain
          value: ["pyroscope.pyroscope.svc.cluster.local"]
        - name: ip
          value: ["10.0.0.1"]
        - name: namespace
          value: ["bookinfo"]
        - name: labels
          value: ["app=productpage"]