{
 "title": "Etcd",
 "description": "Etcd Dashboard for Prometheus metrics scraper",
 "tags": [ "ETCD" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "scb_k8s_name",
    "label": "scb_k8s_name",
    "query": {
     "query": "label_values(etcd_server_has_leader,scb_k8s_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{scb_k8s_name=\"$scb_k8s_name\"}"
    },
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{scb_k8s_name=\"$scb_k8s_name\"} / etcd_server_quota_backend_bytes{scb_k8s_name=\"$scb_k8s_name\"})*100"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_keys_total{scb_k8s_name=\"$scb_k8s_name\"}) by (instance)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, le))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, le))"
    },
    {
     "expr": "sum(etcd_server_is_leader{scb_k8s_name=\"$scb_k8s_name\"}) by (instance)"
    },
    {
     "expr": "sum(etcd_debugging_mvcc_db_compaction_keys_total{scb_k8s_name=\"$scb_k8s_name\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Etcd has a leader?",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{scb_k8s_name=\"$scb_k8s_name\"})"
    }
   ]
  },
  {
   "title": "The number of leader changes seen",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{scb_k8s_name=\"$scb_k8s_name\"})"
    }
   ]
  },
  {
   "title": "The total number of failed proposals seen",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total{scb_k8s_name=\"$scb_k8s_name\"})"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "RPC Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{grpc_type=\"unary\", scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "RPC Rate"
    },
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\", scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "RPC Failed Rate"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "sum(etcd_server_proposals_pending{scb_k8s_name=\"$scb_k8s_name\"})",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Compaction rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_debugging_mvcc_db_compaction_keys_total{scb_k8s_name=\"$scb_k8s_name\"}[5m])",
     "legendFormat": "{{ instance }} compact/s"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\", scb_k8s_name=\"$scb_k8s_name\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\", scb_k8s_name=\"$scb_k8s_name\"})",
     "legendFormat": "Watch Streams"
    },
    {
     "expr": "sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\", scb_k8s_name=\"$scb_k8s_name\"}) - sum(grpc_server_handled_total{grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\", scb_k8s_name=\"$scb_k8s_name\"})",
     "legendFormat": "Lease Streams"
    }
   ]
  },
  {
   "title": "The total number of consensus proposals committed",
   "type": "graph",
   "description": "Offers_committed_total записывает общее количество принятых консенсусных предложений. Этот показатель должен увеличиваться со временем, если кластер исправен. Несколько здоровых членов кластера etcd могут одновременно иметь разное общее количество подтвержденных предложений. Это несоответствие может быть связано с восстановлением от сверстников после запуска, отставанием от лидера или тем, что он является лидером и, следовательно, имеет наибольшее количество коммитов. Важно отслеживать эту метрику для всех участников кластера; постоянно большое отставание между отдельным участником и его лидером указывает на то, что участник медлителен или нездоров.\n\nOffers_applied_total записывает общее количество примененных консенсусных предложений. Сервер etcd применяет каждое принятое предложение асинхронно. Разница между Offers_committed_total и Offers_applied_total обычно должна быть небольшой (в пределах нескольких тысяч даже при высокой нагрузке). Если разница между ними продолжает расти, это означает, что сервер etcd перегружен. Это может произойти при применении дорогостоящих запросов, таких как запросы с большим диапазоном или большие операции txn.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "total number of consensus proposals committed"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "total number of consensus proposals applied"
    }
   ]
  },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_received_bytes_total{scb_k8s_name=\"$scb_k8s_name\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic In"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_network_client_grpc_sent_bytes_total{scb_k8s_name=\"$scb_k8s_name\"}[5m])",
     "legendFormat": "{{instance}} Client Traffic Out"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_received_bytes_total{scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic In"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Peer Traffic Out"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total{scb_k8s_name=\"$scb_k8s_name\"}[1m]))",
     "legendFormat": "The total number of bytes received by grpc clients"
    },
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total{scb_k8s_name=\"$scb_k8s_name\"}[1m]))",
     "legendFormat": "The total number of bytes sent to grpc clients"
    }
   ]
  },
  { "title": "Duratation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  {
   "title": "Defrag time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_disk_backend_defrag_duration_seconds_sum{scb_k8s_name=\"$scb_k8s_name\"}[1m])",
     "legendFormat": "{{ instance }} latency distributions of defrag"
    }
   ]
  },
  {
   "title": "Slow operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_server_slow_apply_total{scb_k8s_name=\"$scb_k8s_name\"}[5m])",
     "legendFormat": "{{ instance }} slow applies"
    },
    {
     "expr": "rate(etcd_server_slow_read_indexes_total{scb_k8s_name=\"$scb_k8s_name\"}[5m])",
     "legendFormat": "{{ instance }}  slow read indexes"
    }
   ]
  },
  {
   "title": "Proposals pending",
   "type": "graph",
   "description": "указывает, сколько предложений поставлено в очередь для фиксации. Рост количества ожидающих предложений указывает на высокую клиентскую нагрузку или на то, что участник не может принять предложения.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_server_proposals_pending{scb_k8s_name=\"$scb_k8s_name\"})",
     "legendFormat": "{{ instance }} Proposals pending"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{scb_k8s_name=\"$scb_k8s_name\"}",
     "legendFormat": "{{instance}} DB Size"
    },
    {
     "expr": "etcd_mvcc_db_total_size_in_use_in_bytes{scb_k8s_name=\"$scb_k8s_name\"}",
     "legendFormat": "Used bytes {{instance}}"
    }
   ]
  },
  {
   "title": "Compacted Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_debugging_mvcc_db_compaction_keys_total{scb_k8s_name=\"$scb_k8s_name\"}[5m])",
     "legendFormat": "{{ instance }} keys compacted "
    }
   ]
  },
  {
   "title": "Disks operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_disk_wal_fsync_duration_seconds_sum{scb_k8s_name=\"$scb_k8s_name\"}[1m]))",
     "legendFormat": "\tThe latency distributions of fsync called by wal"
    },
    {
     "expr": "sum(rate(etcd_disk_backend_commit_duration_seconds_sum{scb_k8s_name=\"$scb_k8s_name\"}[1m]))",
     "legendFormat": "The latency distributions of commit called by backend"
    }
   ]
  },
  {
   "title": "Disks operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_disk_wal_fsync_duration_seconds_sum{scb_k8s_name=\"$scb_k8s_name\"}[1m])",
     "legendFormat": "{{ instance }} The latency distributions of fsync called by wal"
    },
    {
     "expr": "rate(etcd_disk_backend_commit_duration_seconds_sum{scb_k8s_name=\"$scb_k8s_name\"}[1m])",
     "legendFormat": "{{ instance }} The latency distributions of commit called by backend"
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_server_heartbeat_send_failures_total{scb_k8s_name=\"$scb_k8s_name\"}[1m])",
     "legendFormat": "{{ instance }} heartbeat  failures"
    },
    {
     "expr": "rate(etcd_server_health_failures{scb_k8s_name=\"$scb_k8s_name\"}[1m])",
     "legendFormat": "{{ instance }} health failures"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(etcd_server_leader_changes_seen_total{scb_k8s_name=\"$scb_k8s_name\"}[1d])",
     "legendFormat": "{{instance}} Total Leader Elections Per Day"
    }
   ]
  },
  {
   "title": "Error GRPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\", scb_k8s_name=\"$scb_k8s_name\"}[2m])) BY (grpc_service, grpc_method) / sum(rate(grpc_server_handled_total{scb_k8s_name=\"$scb_k8s_name\"}[2m])) BY (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_method}} || {{grpc_service}} "
    }
   ]
  },
  {
   "title": "Snapshot duration",
   "type": "graph",
   "description": "Abnormally high snapshot duration (snapshot_save_total_duration_seconds) indicates disk issues and might cause the cluster to be unstable.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_debugging_snap_save_total_duration_seconds_sum{scb_k8s_name=\"$scb_k8s_name\"}[1m]))",
     "legendFormat": "The total latency distributions of save called by snapshot"
    }
   ]
  }
 ]
}