{
 "title": "K8S Control Plane",
 "description": "Metrics for API Server, Controller and Scheduler.",
 "tags": [ "Kubernetes-components" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "scb_k8s_name",
    "label": "scb_k8s_name",
    "query": {
     "query": "label_values(up{job=\"kubernetes-apiservers\"},scb_k8s_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API Server Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Текущие запросы ",
   "type": "timeseries",
   "description": "Текущие запросы ",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(apiserver_current_inflight_requests{job=\"kubernetes-apiservers\", scb_k8s_name=~\"$scb_k8s_name\"}) by (requestKind)",
     "legendFormat": "{{requestKind}}"
    }
   ]
  },
  {
   "title": "API-сервер - HTTP-запросы по методу",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total{job=\"kubernetes-apiservers\", scb_k8s_name=~\"$scb_k8s_name\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Длительность ответа API-сервера (секунды)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_sum{job=\"kubernetes-apiservers\", scb_k8s_name=~\"$scb_k8s_name\", verb!~\"WATCH|CONNECT\"}[5m])) ",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "API Server Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"kubernetes-apiservers\", scb_k8s_name=~\"$scb_k8s_name\", code=~\"^(?:4..)$|^(?:5..)$|<error>\"}[5m])) by (code)>0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Kube Controller Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Has Leader?",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(leader_election_master_status{job=\"kube-controller-manager\", scb_k8s_name=\"$scb_k8s_name\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Рабочая Очередь / Work Queue Depth",
     "type": "timeseries",
     "description": "Текущая глубина очереди работ ",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(workqueue_depth{job=\"kube-controller-manager\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, name)",
       "legendFormat": "{{instance}} {{name}}"
      }
     ]
    },
    {
     "title": "Скорость добавления рабочей очереди",
     "type": "timeseries",
     "description": "Количество добавлений, ОБРАБОТАННЫХ рабочей очередью ",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(workqueue_adds_total{job=\"kube-controller-manager\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, name)",
       "legendFormat": "{{instance}} {{name}}"
      }
     ]
    },
    {
     "title": "99 pricentile latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le, service, verb) (rate(rest_client_request_duration_seconds_bucket{job=\"kube-controller-manager\", scb_k8s_name=\"$scb_k8s_name\"}[1m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Status code ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 15 },
     "targets": [
      {
       "expr": "sum by(method, container, code) (rate(rest_client_requests_total{code=~\"5..|4..|<error>\", job=\"kube-controller-manager\", scb_k8s_name=\"$scb_k8s_name\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kube Scheduler Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Has Leader?",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(leader_election_master_status{job=\"kube-scheduler\", scb_k8s_name=\"$scb_k8s_name\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Попытки планировщика выполнение задач",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(scheduler_schedule_attempts_total{job=\"kube-scheduler\", scb_k8s_name=\"$scb_k8s_name\"}[1m])) by (result)",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Scheduler Duration ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(scheduler_e2e_scheduling_duration_seconds_sum{job=\"kube-scheduler\", scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
       "legendFormat": "Duration"
      }
     ]
    },
    {
     "title": "Scheduling latency 99th Quantile",
     "type": "timeseries",
     "description": "Задержка планирования в секундах (алгоритм планирования + привязка). \n",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(scheduler_e2e_scheduling_duration_seconds_bucket{job=\"kube-scheduler\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, le))",
       "legendFormat": "{{instance}} e2e"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(scheduler_binding_duration_seconds_bucket{job=\"kube-scheduler\",instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, le))",
       "legendFormat": "{{instance}} binding"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(scheduler_scheduling_algorithm_duration_seconds_bucket{job=\"kube-scheduler\",instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, le))",
       "legendFormat": "{{instance}} scheduling algorithm"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(scheduler_volume_scheduling_duration_seconds_bucket{job=\"kube-scheduler\",instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, le))",
       "legendFormat": "{{instance}} volume"
      }
     ]
    },
    {
     "title": "Error Status code ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 16 },
     "targets": [
      {
       "expr": "sum by(method, container, code) (rate(rest_client_requests_total{code=~\"5..|4..|<error>\", job=\"kube-scheduler\", scb_k8s_name=\"$scb_k8s_name\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "API Server Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Успешные ответы API-сервера / API Server Success",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{job=\"kubernetes-apiservers\", scb_k8s_name=~\"$scb_k8s_name\", code!~\"^(?:4..)$|^(?:5..)$\"}[5m])) by (code)>0",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "API Server Requests (by Verb)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 7, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{job=\"kubernetes-apiservers\", scb_k8s_name=~\"$scb_k8s_name\"}[5m])) by (verb)",
       "legendFormat": "{{verb}}"
      }
     ]
    },
    {
     "title": "Запросы к API (по ресурсам) / API Requests (by Resource)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{job=\"kubernetes-apiservers\", scb_k8s_name=~\"$scb_k8s_name\"}[5m])) by (resource)",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "Запросы API от клиента (не связанные с kube-*)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{job=\"kubernetes-apiservers\", scb_k8s_name=~\"$scb_k8s_name\", client!~\"kubelet.*|kube-scheduler.*|kube-controller.*|kube-apiserver.*|kube-proxy.*\"}[5m])) by (client)>0",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "API Server Requests by server",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "sum(rate(apiserver_request_total{job=\"kubernetes-apiservers\", scb_k8s_name=~\"$scb_k8s_name\"}[5m])) by (instance)>0",
       "legendFormat": "{{instance}} ",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "API Server Response Duration - CONNECT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_duration_seconds_sum{job=\"kubernetes-apiservers\", verb=~\"CONNECT\"}[5m])) by (resource)/sum(rate(apiserver_request_duration_seconds_count{job=\"kubernetes-apiservers\",verb=~\"CONNECT\"}[5m])) by (resource)>0",
       "legendFormat": "{{resource}}"
      }
     ]
    }
   ]
  },
  { "title": "Etcd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Etcd - Health Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"etcd\", scb_k8s_name=~\"$scb_k8s_name\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Compaction rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_debugging_mvcc_db_compaction_keys_total{scb_k8s_name=\"$scb_k8s_name\"}[5m])",
     "legendFormat": "{{ instance }} compact/s"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_server_heartbeat_send_failures_total{scb_k8s_name=\"$scb_k8s_name\"}[2m])",
     "legendFormat": "{{ instance }} heartbeat  failures"
    },
    {
     "expr": "etcd_server_health_failures{scb_k8s_name=\"$scb_k8s_name\"}",
     "legendFormat": "{{ instance }} health failures"
    }
   ]
  }
 ]
}