{
 "title": "Kubernetes / Controller Manager",
 "description": "prometheus operator ",
 "tags": [
  "kubernetes-mixin",
  "kube-controller-manager"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "scb_k8s_name",
    "label": "scb_k8s_name",
    "query": {
     "query": "label_values(up{job=\"kube-controller-manager\"},scb_k8s_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"kube-controller-manager\", scb_k8s_name=\"$scb_k8s_name\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kube-controller-manager\", scb_k8s_name=\"$scb_k8s_name\"})"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "description": "Количество добавлений, ОБРАБОТАННЫХ рабочей очередью ",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"kube-controller-manager\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "timeseries",
   "description": "Текущая глубина очереди работ ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{job=\"kube-controller-manager\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "timeseries",
   "description": "Как долго в сек. элемент остается в рабочей очереди до запроса ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"kube-controller-manager\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, name, le))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Срез кол-ва запросов url к методу ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(url, verb) (rate(rest_client_request_duration_seconds_bucket{job=\"kube-controller-manager\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status code ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by(method, container, code) (rate(rest_client_requests_total{job=\"kube-controller-manager\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "description": "Количество HTTP-запросов, разделенных по коду состояния, методу и хосту.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\", instance=~\"$instance\",code=~\"2..\", scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\", instance=~\"$instance\",code=~\"3..\", scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\", instance=~\"$instance\",code=~\"4..\", scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-controller-manager\", instance=~\"$instance\",code=~\"5..\", scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Post Request Latency 99th Quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=\"kube-controller-manager\", instance=~\"$instance\", verb=\"POST\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "99 pricentile latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, service, verb) (rate(rest_client_request_duration_seconds_bucket{job=\"kube-controller-manager\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Get Request Latency 99th Quantile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=\"kube-controller-manager\", instance=~\"$instance\", verb=\"GET\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-controller-manager\",instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-controller-manager\",instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"kube-controller-manager\",instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}