{
 "title": "Kubernetes CoreDNS",
 "description": "A dashboard for the CoreDNS DNS server ",
 "tags": [
  "dns",
  "coredns"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DS", "query": "prometheus" },
   {
    "name": "kubernetes_node",
    "label": "kubernetes_node",
    "query": {
     "query": "label_values(coredns_build_info, kubernetes_node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "By kubernetes node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "kubernetes_node",
   "targets": [
    {}
   ]
  },
  {
   "title": "CoreDNS Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coredns_build_info{kubernetes_node=\"$kubernetes_node\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Requests (total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{kubernetes_node=~\"$kubernetes_node\"}[5m])) by (proto) or\nsum(rate(coredns_dns_requests_total{kubernetes_node=~\"$kubernetes_node\"}[5m])) by (proto)",
     "legendFormat": "{{proto}}"
    }
   ]
  },
  {
   "title": "Requests (by qtype)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_type_count_total{kubernetes_node=~\"$kubernetes_node\"}[5m])) by (type) or \nsum(rate(coredns_dns_requests_total{kubernetes_node=~\"$kubernetes_node\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_count_total{kubernetes_node=~\"$kubernetes_node\"}[5m])) by (zone) or\nsum(rate(coredns_dns_requests_total{kubernetes_node=~\"$kubernetes_node\"}[5m])) by (zone)",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Requests (DO bit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_request_do_count_total{kubernetes_node=~\"$kubernetes_node\"}[5m])) or\nsum(rate(coredns_dns_do_requests_total{kubernetes_node=~\"$kubernetes_node\"}[5m]))",
     "legendFormat": "DO"
    },
    {
     "expr": "sum(rate(coredns_dns_request_count_total{kubernetes_node=~\"$kubernetes_node\"}[5m])) or\nsum(rate(coredns_dns_requests_total{kubernetes_node=~\"$kubernetes_node\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requests (size, udp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{kubernetes_node=~\"$kubernetes_node\",proto=\"udp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:99 "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{kubernetes_node=~\"$kubernetes_node\",proto=\"udp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{kubernetes_node=~\"$kubernetes_node\",proto=\"udp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  {
   "title": "Requests (size,tcp)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{kubernetes_node=~\"$kubernetes_node\",proto=\"tcp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:99 "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{kubernetes_node=~\"$kubernetes_node\",proto=\"tcp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{kubernetes_node=~\"$kubernetes_node\",proto=\"tcp\"}[5m])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  {
   "title": "Responses (by rcode)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{kubernetes_node=~\"$kubernetes_node\"}[5m])) by (rcode) or\nsum(rate(coredns_dns_responses_total{kubernetes_node=~\"$kubernetes_node\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Responses (duration)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{kubernetes_node=~\"$kubernetes_node\"}[5m])) by (le, job))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{kubernetes_node=~\"$kubernetes_node\"}[5m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_duration_seconds_bucket{kubernetes_node=~\"$kubernetes_node\"}[5m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Cache (size)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(coredns_cache_size{kubernetes_node=~\"$kubernetes_node\"}) by (type) or\nsum(coredns_cache_entries{kubernetes_node=~\"$kubernetes_node\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache (hitrate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{kubernetes_node=~\"$kubernetes_node\"}[5m])) by (type)",
     "legendFormat": "hits:{{type}}"
    },
    {
     "expr": "sum(rate(coredns_cache_misses_total{kubernetes_node=~\"$kubernetes_node\"}[5m])) by (type)",
     "legendFormat": "misses"
    }
   ]
  }
 ]
}