{
 "title": "Kubernetes Events Dashboard",
 "description": "Kubernetes Events Dashboard(Loki as DataSource)",
 "tags": [
  "Loki",
  "kuber-event"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "K8S_clusters",
    "label": "K8S_clusters",
    "query": {}
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(container_memory_usage_bytes,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Общие показатели по кластеру ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kubernetes Events Overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (type) (count_over_time({k8s_events=\"$K8S_clusters\"}| json |  __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Warning Enents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({k8s_events=\"$K8S_clusters\"}| json | type = \"Warning\" | __error__=\"\" [$__interval]))",
     "legendFormat": "Warning"
    }
   ]
  },
  {
   "title": "Image Pull Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({k8s_events=\"$K8S_clusters\"}|= \"Error: ImagePullBackOff\" | json | reason = \"Failed\"  | line_format \"{{ .message }}\"| __error__=\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Container Crashed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({k8s_events=\"$K8S_clusters\"}| json | reason = \"BackOff\"| __error__=\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Container OOM Killed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({k8s_events=\"$K8S_clusters\"} | json | reason=\"OOMKilling\"| __error__=\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Liveness Check Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({k8s_events=\"$K8S_clusters\"} | json | reason = \"Killing\" | __error__=\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Schedule Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({k8s_events=\"$K8S_clusters\"}| json | reason = \"FailedScheduling\"| __error__=\"\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Pod Evicted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({k8s_events=\"$K8S_clusters\"} | json | reason = \"TaintManagerEviction\"| __error__=\"\"[$__interval]))"
    }
   ]
  },
  { "title": "TOP 20  Kubernetes Events", "gridPos": { "h": 14, "w": 12, "x": 0, "y": 15 } },
  {
   "title": "Kubernetes Events Source",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({k8s_events=\"$K8S_clusters\"}| json| __error__=\"\"[$__interval])) by (source_component)",
     "legendFormat": "{{source_component}}"
    }
   ]
  },
  {
   "title": "Kubernetes  Events Type",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({k8s_events=\"$K8S_clusters\"}| json| __error__=\"\"[$__interval])) by (involvedObject_kind)",
     "legendFormat": "{{involvedObject_kind}}"
    }
   ]
  },
  {
   "title": "Healthy failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (reason, metadata_namespace) (rate({k8s_clusters=~\"$K8S_clusters\"} | json | line_format \"{{.Line}}\" | reason=~\"Unhealthy\" [5m] ))",
     "legendFormat": "{{reason}}: namespace {{metadata_namespace}}"
    }
   ]
  },
  {
   "title": "Run service BackOff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by (reason, metadata_namespace) (rate({k8s_clusters=~\"$K8S_clusters\"} | json | line_format \"{{.Line}}\" | reason=~\"BackOff\" [5m] ))",
     "legendFormat": "{{reason}}: namespace {{metadata_namespace}}"
    }
   ]
  },
  {
   "title": "OOM Node Events in cluster $K8S_clusters",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{k8s_events=\"$K8S_clusters\"} | json | line_format \"{{.Line}}\" | reason=~\"SystemOOM|OOMKilling\" "
    }
   ]
  },
  {
   "title": "Сообщения по namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Events in cluster $K8S_clusters in namespace: $namespace",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "{k8s_events=\"$K8S_clusters\"} | json | line_format \"{{.Line}}\" | involvedObject_namespace=~\"$namespace\" | type!=\"Normal\""
      }
     ]
    },
    {
     "title": "Events in cluster $K8S_clusters in namespace: $namespace",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "{k8s_events=\"$K8S_clusters\"} | json | line_format \"{{.Line}}\" | involvedObject_namespace=~\"$namespace\""
      }
     ]
    }
   ]
  },
  {
   "title": "Все events по кластеру",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "ALL Error Node Events in cluster $K8S_clusters",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "{k8s_events=\"$K8S_clusters\"} | json | line_format \"{{.Line}}\" | involvedObject_kind=\"Node\""
      }
     ]
    },
    {
     "title": "Kubernetes All Live Events",
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "{k8s_events=\"$K8S_clusters\"} | json | line_format \"{{.Line}}\" "
      }
     ]
    }
   ]
  }
 ]
}