{
 "title": "Kubernetes / Scheduler",
 "description": "K8s scheduler",
 "tags": [
  "kubernetes-mixin",
  "kube-scheduler"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "scb_k8s_name",
    "label": "scb_k8s_name",
    "query": {
     "query": "label_values(up{job=\"kube-scheduler\"},scb_k8s_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(process_cpu_seconds_total{job=\"kube-scheduler\", scb_k8s_name=\"$scb_k8s_name\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kube-scheduler\", scb_k8s_name=\"$scb_k8s_name\"})"
    }
   ]
  },
  {
   "title": "Scheduling Rate",
   "type": "timeseries",
   "description": "Задержка планирования E2e в секундах (алгоритм планирования + привязка). Этот показатель заменен на scheduling_attempt_duration_seconds.",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(scheduler_e2e_scheduling_duration_seconds_count{job=\"kube-scheduler\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} e2e"
    },
    {
     "expr": "sum(rate(scheduler_binding_duration_seconds_count{job=\"kube-scheduler\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} binding"
    },
    {
     "expr": "sum(rate(scheduler_scheduling_algorithm_duration_seconds_count{job=\"kube-scheduler\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} scheduling algorithm"
    },
    {
     "expr": "sum(rate(scheduler_volume_scheduling_duration_seconds_count{job=\"kube-scheduler\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} volume"
    }
   ]
  },
  {
   "title": "Scheduling latency 99th Quantile",
   "type": "timeseries",
   "description": "Задержка планирования в секундах (алгоритм планирования + привязка). \n",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scheduler_e2e_scheduling_duration_seconds_bucket{job=\"kube-scheduler\",instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} e2e"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scheduler_binding_duration_seconds_bucket{job=\"kube-scheduler\",instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} binding"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scheduler_scheduling_algorithm_duration_seconds_bucket{job=\"kube-scheduler\",instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} scheduling algorithm"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(scheduler_volume_scheduling_duration_seconds_bucket{job=\"kube-scheduler\",instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} volume"
    }
   ]
  },
  {
   "title": "Queue duration",
   "type": "timeseries",
   "description": "Сколько времени (в секундах) элемент остается в рабочей очереди перед запросом.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"kube-scheduler\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (instance, name, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Очередь сред значение",
   "type": "timeseries",
   "description": "Количество модулей, добавленных в очереди планирования, в разбивке по событию и типу очереди.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(scheduler_queue_incoming_pods_total{job=\"kube-scheduler\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])) by (event, queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Задачи по плнированию ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(scheduler_plugin_execution_duration_seconds_bucket{job=\"kube-scheduler\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[2m])) by (extension_point, plugin, status)",
     "legendFormat": "{{plugin}}  {{status}}"
    }
   ]
  },
  {
   "title": "Status code ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(method, container, code) (rate(rest_client_requests_total{job=\"kube-scheduler\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "description": "Количество HTTP-запросов, разделенных по коду состояния, методу и хосту.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-scheduler\", instance=~\"$instance\",code=~\"2..\", scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-scheduler\", instance=~\"$instance\",code=~\"3..\", scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-scheduler\", instance=~\"$instance\",code=~\"4..\", scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-scheduler\", instance=~\"$instance\",code=~\"5..\", scb_k8s_name=\"$scb_k8s_name\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Post Request Latency 99th Quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=\"kube-scheduler\", instance=~\"$instance\", verb=\"POST\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "99 pricentile latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, service, verb) (rate(rest_client_request_duration_seconds_bucket{job=\"kube-scheduler\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-scheduler\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-scheduler\", instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"kube-scheduler\",instance=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}