{
 "title": "Kubernetes / Kubelet",
 "description": "K8s kubelet",
 "tags": [ "kubelet" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "scb_k8s_name",
    "label": "scb_k8s_name",
    "query": {
     "query": "label_values(up{job=\"kube-scheduler\"},scb_k8s_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kubelet_runtime_operations_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_node_name{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "description": "общие кол-во работ. подов ",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Running Container",
   "type": "stat",
   "description": "Общие кол-во работающих контейнеров",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Actual Volume Count",
   "type": "stat",
   "description": "Количество томов в диспетчере томов , действительное состояние",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(volume_manager_total_volumes{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\", state=\"actual_state_of_world\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Desired Volume Count",
   "type": "stat",
   "description": "желаемое состояние",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(volume_manager_total_volumes{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\",state=\"desired_state_of_world\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Config Error Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_node_config_error{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "График по запылённости подов ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "abs((kubelet_running_pods{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"})[1m] )",
     "legendFormat": "{{instance}}"
    },
    { "expr": "110", "legendFormat": "Limits " }
   ]
  },
  {
   "title": "Общая Емкость кластера по CPU request",
   "type": "stat",
   "description": "В расчете не участвуют кластеровые ноды  ",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum ((sum by (node) (kube_pod_container_resource_requests{resource=\"cpu\", node=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\" , node!~\".*c[1-3]\", release!=\"rancher-monitoring\"} )) / sum((count(count(node_cpu_seconds_total{mode=\"system\", scb_k8s_name=\"$scb_k8s_name\", kubernetes_node=~\"$instance\", kubernetes_node!~\".*c[1-3]\"}) by (cpu, kubernetes_node))) ) ) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Общая Емкость кластера по MEM request",
   "type": "stat",
   "description": "В расчете не участвуют кластеровые ноды  ",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum ((sum by (node) (kube_pod_container_resource_requests{resource=\"memory\", node=~\"$instance\", scb_k8s_name=\"$scb_k8s_name\", node!~\".*c[1-3]\"} ) ) / sum ( (sum(node_memory_MemTotal_bytes{scb_k8s_name=\"$scb_k8s_name\", kubernetes_node=~\"$instance\", kubernetes_node!~\".*c[1-3]\"})) ) ) ) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Общая Емкость кластера заполнения подов в кластере или на ноде ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\", kubernetes_node!~\".*c[1-3]\"}) / ((sum(kubelet_node_name{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\", kubernetes_node!~\".*c[1-3]\"}) ) * 110) * 100"
    }
   ]
  },
  {
   "title": "кол-во запущенных подов на ноде ",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kubelet_running_pods{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Error ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Operation Docker Error Rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_docker_operations_errors_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, operation_type)",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Operation Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, operation_type)",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "evictions pods",
   "type": "timeseries",
   "description": "evicted pods",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_evictions{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "podsandbox Error Rate ",
   "type": "timeseries",
   "description": "Совокупное количество ошибок при работе с run_pods и box в разбивке по классам среды выполнения.Обработчик.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_run_podsandbox_errors_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, operation_type)",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Operation network Error Rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_network_plugin_operations_errors_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, operation_type)",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Storage Operation Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(storage_operation_errors_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, operation_name, volume_plugin)",
     "legendFormat": "{{instance}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "RPC Error Rate  5xx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\",code=~\"5.*\"}[5m]) ) by (instance, code,scb_k8s_name,method)",
     "legendFormat": "{{ instance }} | {{ method }} |  {{ code }}"
    }
   ]
  },
  {
   "title": "RPC Error Rate 4xx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\",code=~\"4.*\"}[5m]) ) by (instance, code,scb_k8s_name,method)",
     "legendFormat": "{{ instance }} | {{ method }} |  {{ code }}"
    }
   ]
  },
  {
   "title": "Storage Operation Duration 99th quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(storage_operation_duration_seconds_bucket{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, operation_name, volume_plugin, le))",
     "legendFormat": "{{instance}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  },
  {
   "title": "Cgroup manager operation rate",
   "type": "timeseries",
   "description": "Длительность операций менеджера группы в секундах. В разбивке по методам.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_cgroup_manager_duration_seconds_count{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, operation_type)",
     "legendFormat": "{{operation_type}}"
    }
   ]
  },
  {
   "title": "Cgroup manager 99th quantile",
   "type": "timeseries",
   "description": "Длительность операций менеджера группы в секундах. В разбивке по объектам.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_cgroup_manager_duration_seconds_bucket{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, operation_type, le))",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "PLEG relist rate",
   "type": "timeseries",
   "description": "Генератор событий жизненного цикла модуля\nВремя в секундах для повторного внесения модулей в список PLEG.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_pleg_relist_duration_seconds_count{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PLEG relist interval",
   "type": "timeseries",
   "description": "интервал повторного включения в список",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_interval_seconds_bucket{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PLEG relist duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_duration_seconds_bucket{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Lattency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Operation duration 99th quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, operation_type, le))",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile",
   "type": "timeseries",
   "description": "Задержка запроса в секундах. Разбивка по глаголу и хосту",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, verb, url, le))",
     "legendFormat": "{{instance}} {{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Pod Start Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_pod_start_duration_seconds_count{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} pod"
    },
    {
     "expr": "sum(rate(kubelet_pod_worker_duration_seconds_count{cluster=\"$cluster\",job=\"kubelet\", metrics_path=\"/metrics\",instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} worker"
    }
   ]
  },
  {
   "title": "Pod Start Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pod_start_duration_seconds_count{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} pod"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pod_worker_duration_seconds_bucket{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}} worker"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "RPC Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Operation Rate",
   "type": "timeseries",
   "description": "Совокупное количество операций во время выполнения в разбивке по типу операции",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_total{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (operation_type, instance)",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Storage Operation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(storage_operation_duration_seconds_count{scb_k8s_name=\"$scb_k8s_name\", job=\"kubernetes-nodes\", instance=~\"$instance\"}[5m])) by (instance, operation_name, volume_plugin)",
     "legendFormat": "{{instance}} {{operation_name}} {{volume_plugin}}"
    }
   ]
  }
 ]
}