{
 "title": "Kuber-Envoy_LB",
 "description": "Envoy proxy monitoring Dashboard with cluster and host level templates. ",
 "tags": [
  "Kuber-LB",
  "envoy"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "scb_k8s_name",
    "label": "scb_k8s_name",
    "query": {
     "query": "label_values(envoy_server_live,scb_k8s_name)"
    }
   },
   {
    "name": "lb",
    "label": "lb",
    "query": {
     "query": "label_values(envoy_server_live,lb)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(envoy_server_live{scb_k8s_name=~\"$scb_k8s_name\", lb=\"$lb\"},instance)"
    }
   },
   {
    "name": "stream",
    "label": "Downstream",
    "query": {
     "query": "label_values(envoy_tcp_downstream_cx_tx_bytes_total, envoy_tcp_prefix)"
    }
   },
   {
    "name": "upstream",
    "label": "upstream",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_active, envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Live servers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(envoy_server_uptime{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "% нагрузки Envoy",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "envoy_overload_envoy_resource_monitors_fixed_heap_pressure{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} -  %% нагрузки "
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downstream Total  CX Counter  rate 10 SEC (delta)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(envoy_tcp_downstream_cx_total{envoy_tcp_prefix=~\"$stream\",instance=~\"$instance\"}[10s])",
       "legendFormat": "{{zone}}({{envoy_tcp_prefix}} - {{ae_source}})"
      }
     ]
    },
    {
     "title": "Upstream total active connections ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "envoy_cluster_upstream_cx_active{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"}",
       "legendFormat": "{{zone}}({{envoy_cluster_name}} - {{ae_source}})"
      }
     ]
    },
    {
     "title": "Downstream Network Traffic 10 SEC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(envoy_tcp_downstream_cx_rx_bytes_total{envoy_tcp_prefix=~\"$stream\",instance=~\"$instance\"}[10s])",
       "legendFormat": "{{zone}} ({{envoy_tcp_prefix}} - {{ae_source}}) - in"
      },
      {
       "expr": "rate(envoy_tcp_downstream_cx_tx_bytes_total{envoy_tcp_prefix=~\"$stream\",instance=~\"$instance\"}[10s])",
       "legendFormat": "{{zone}} ({{envoy_tcp_prefix}} - {{ae_source}}) - out"
      }
     ]
    },
    {
     "title": "Upstream total requests 10 SEC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(envoy_cluster_upstream_rq_total{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"}[10s])",
       "legendFormat": "{{zone}}({{envoy_cluster_name}} - {{ae_source}})"
      }
     ]
    },
    {
     "title": "Downstream Bytes Buffered 10 SEC",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(envoy_tcp_downstream_cx_rx_bytes_buffered{envoy_tcp_prefix=~\"$stream\",instance=~\"$instance\"}[10s])",
       "legendFormat": "{{zone}}({{envoy_tcp_prefix}} - {{ae_source}}) -  IN"
      },
      {
       "expr": "rate(envoy_tcp_downstream_cx_tx_bytes_buffered{envoy_tcp_prefix=~\"$stream\",instance=~\"$instance\"}[10s])",
       "legendFormat": "{{zone}}({{envoy_tcp_prefix}} - {{ae_source}}) - OUT"
      }
     ]
    },
    {
     "title": "Upstream Network Traffic 10 SEC",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(envoy_cluster_upstream_cx_rx_bytes_total{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"}[10s])",
       "legendFormat": "{{zone}} ({{envoy_cluster_name}} - {{ae_source}}) - in"
      },
      {
       "expr": "rate(envoy_cluster_upstream_cx_tx_bytes_total{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"}[10s])",
       "legendFormat": "{{zone}} ({{envoy_cluster_name}} - {{ae_source}}) - out"
      }
     ]
    },
    {
     "title": "Envoy нагрузка",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "envoy_overload_envoy_resource_monitors_fixed_heap_failed_updates{instance=~\"$instance\"}",
       "legendFormat": "{{zone}}{{instance}} -   Кол-во  неудачных обновлений нагрузки"
      },
      {
       "expr": "envoy_overload_envoy_resource_monitors_fixed_heap_skipped_updates{instance=~\"$instance\"}",
       "legendFormat": "{{zone}}{{instance}} -  Кол-во  пропущенных обновлений нагрузки"
      },
      {
       "expr": "envoy_overload_envoy_resource_monitors_fixed_heap_pressure{instance=~\"$instance\"}",
       "legendFormat": "{{zone}}{{instance}} -  Нагрузка %%"
      }
     ]
    },
    {
     "title": "Upstream active requests rate  10 SEC",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(envoy_cluster_upstream_rq_active{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"}[10s])",
       "legendFormat": "{{zone}}  ({{envoy_cluster_name}} - {{ae_source}} "
      }
     ]
    },
    {
     "title": "Сonnections closed due to idle timeout rate  10 SEC",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(envoy_tcp_idle_timeout{envoy_tcp_prefix=~\"$stream\",instance=~\"$instance\"}[10s])",
       "legendFormat": "{{zone}}  ({{envoy_tcp_prefix}} - {{ae_source}} "
      }
     ]
    }
   ]
  },
  { "title": "Capability ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Количество запросов в очереди",
   "type": "timeseries",
   "description": "Количество запросов в очереди.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_pending_total{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"})[5m]",
     "legendFormat": "({{envoy_cluster_name}} - {{instance}}  - {{lb}})"
    }
   ]
  },
  {
   "title": "Всего активных подключений",
   "type": "timeseries",
   "description": "Всего активных подключений.Обрати внимание чтобы не упирался в потолок ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"}",
     "legendFormat": "{{zone}}({{envoy_cluster_name}} - {{ae_source}})"
    }
   ]
  },
  {
   "title": "Количество запросов, превышающее лимит, было зафиксировано в течение последних 5 минут.",
   "type": "timeseries",
   "description": "Количество запросов, превышающее лимит, было зафиксировано в течение последних 5 минут.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_cx_max_requests{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"})[5m]",
     "legendFormat": "({{envoy_cluster_name}} - {{instance}}  - {{lb}})"
    }
   ]
  },
  {
   "title": "Превышено допустимое количество попыток подключения за последние 5 минут",
   "type": "timeseries",
   "description": "Превышено допустимое количество попыток подключения за последние 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_cx_connect_attempts_exceeded{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"})[5m]",
     "legendFormat": "({{envoy_cluster_name}} - {{instance}}  - {{lb}})"
    }
   ]
  },
  {
   "title": "Количество запросов, которые были отклонены из-за отказа узла",
   "type": "timeseries",
   "description": "Количество запросов, которые были отклонены из-за отказа узла",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_pending_failure_eject{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"}[5m])",
     "legendFormat": "({{envoy_cluster_name}} - {{instance}}  - {{lb}})"
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Обнаружены ошибки привязки к порту (bind errors)",
   "type": "timeseries",
   "description": "Обнаружены ошибки привязки к порту (bind errors)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_bind_errors{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"})[5m]",
     "legendFormat": "({{envoy_cluster_name}} - {{instance}}  - {{lb}})"
    }
   ]
  },
  {
   "title": "Обнаружены сбои при попытках подключения к upstream",
   "type": "timeseries",
   "description": "Обнаружены сбои при попытках подключения к upstream",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_cx_connect_fail{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"})[5m]",
     "legendFormat": "({{envoy_cluster_name}} - {{instance}}  - {{lb}})"
    }
   ]
  },
  {
   "title": "Обнаружены таймауты подключения к upstream",
   "type": "timeseries",
   "description": "Обнаружены таймауты подключения к upstream",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_cx_connect_timeout{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"})[5m]",
     "legendFormat": "({{envoy_cluster_name}} - {{instance}}  - {{lb}})"
    }
   ]
  },
  {
   "title": "Количество запросов, которые были отброшены из-за переполнения очереди",
   "type": "timeseries",
   "description": "Количество запросов, которые были отброшены из-за переполнения очереди",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_pending_overflow{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"})[5m]",
     "legendFormat": "({{envoy_cluster_name}} - {{instance}}  - {{lb}})"
    }
   ]
  },
  {
   "title": "Не осталось доступных здоровых узлов для подключения за последние 5 минут",
   "type": "timeseries",
   "description": "Не осталось доступных здоровых узлов для подключения за последние 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_cx_none_healthy{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"})[5m]",
     "legendFormat": "({{envoy_cluster_name}} - {{instance}}  - {{lb}})"
    }
   ]
  },
  {
   "title": "Количество активных запросов в очереди ",
   "type": "timeseries",
   "description": "Количество активных запросов в очереди ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_pending_active{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"})[5m]",
     "legendFormat": "({{envoy_cluster_name}} - {{instance}}  - {{lb}})"
    }
   ]
  },
  {
   "title": "Обнаружены ошибки подключения",
   "type": "timeseries",
   "description": "Обнаружены ошибки подключения",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_connection_error{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"})[5m]",
     "legendFormat": "({{envoy_cluster_name}} - {{instance}}  - {{lb}})"
    }
   ]
  },
  {
   "title": "Обнаружены ошибки рукопожатия (handshake) ",
   "type": "timeseries",
   "description": "Обнаружены ошибки рукопожатия (handshake) ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_handshake{instance=~\"$instance\",envoy_cluster_name=\"$upstream\"})[5m]",
     "legendFormat": "({{envoy_cluster_name}} - {{instance}}  - {{lb}})"
    }
   ]
  },
  { "title": "Lattencyy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Latency подключения к upstream: 95-й процентиль",
   "type": "timeseries",
   "description": "Latency подключения к upstream: 95-й процентиль",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_cx_connect_ms_bucket[5m])) by (le))",
     "legendFormat": "95 % "
    }
   ]
  }
 ]
}