{
 "title": "Node-Local-Dns",
 "description": "A dashboard for the CoreDNS DNS server with updated metrics for version 1.7.0+.  Based on the CoreDNS 1.7.0+ dashboard by ejkinger",
 "tags": [
  "dns",
  "node-local-dns"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{kubernetes_io_name=\"CoreDNS\"},scb_k8s_name)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{app_kubernetes_io_instance=\"node-local-dns\", scb_k8s_name=\"$cluster\"},instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Latency && Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Zone Rcode dns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\", zone=~\"sovcombank.*\"}[1m])) by (rcode, zone)",
     "legendFormat": "Code: {{rcode}} | Zone: {{zone}}"
    }
   ]
  },
  {
   "title": "Responses (by code)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Responses (latency, internet  sovcombank )",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\", zone=~\"sovcombank.*\"}[5m])) by (le, zone))",
     "legendFormat": "99% {{zone}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_duration_seconds_bucket{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\", zone=~\"sovcombank.*\"}[5m])) by (le, zone))",
     "legendFormat": "90%  {{zone}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_duration_seconds_bucket{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\", zone=~\"sovcombank.*\"}[5m])) by (le, zone))",
     "legendFormat": "50%  {{zone}}"
    }
   ]
  },
  {
   "title": "Responses (latency) ALL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_forward_request_duration_seconds_bucket{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_forward_request_duration_seconds_bucket{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\"}[5m])) by (le))",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "NodeLocalDNSLatency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum without(instance, pod) (rate(coredns_dns_request_duration_seconds_bucket{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\"}[5m])))",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests (by zone)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\"}[5m])) by (zone)",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Requests (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\",app_kubernetes_io_instance=\"node-local-dns\"}[5m])) by (server,kubernetes_node)",
     "legendFormat": "{{kubernetes_node}} {{server}}"
    },
    {
     "expr": "sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\"}[5m]))",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "Cache (hitrate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", type=\"success\", app_kubernetes_io_instance=\"node-local-dns\"}[5m])) / sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\"}[5m]))",
     "legendFormat": "hits: success"
    },
    {
     "expr": "sum(rate(coredns_cache_hits_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", type=\"denial\",app_kubernetes_io_instance=\"node-local-dns\"}[5m])) / sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\"}[5m]))",
     "legendFormat": "hits: denial"
    },
    {
     "expr": "(sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\"}[5m])) - sum(rate(coredns_cache_hits_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", type=\"success\", app_kubernetes_io_instance=\"node-local-dns\"}[5m]))) / sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\"}[5m]))",
     "legendFormat": "misses"
    },
    {
     "expr": "sum(rate(coredns_dnssec_cache_hits_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\"}[5m])) / sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\"}[5m]))",
     "legendFormat": "hits: DNSSEC"
    },
    {
     "expr": "(sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\",app_kubernetes_io_instance=\"node-local-dns\"}[5m])) - sum(rate(coredns_dnssec_cache_hits_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\"}[5m]))) / sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\"}[5m]))",
     "legendFormat": "misses: DNSSEC"
    }
   ]
  },
  {
   "title": "Cache (hitrate) zones=~\"sovcombank.*\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", type=\"success\", zones=~\"sovcombank.*\",app_kubernetes_io_instance=\"node-local-dns\"}[5m])) / sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", zones=~\"sovcombank.*\",app_kubernetes_io_instance=\"node-local-dns\"}[5m]))",
     "legendFormat": "hits: success"
    },
    {
     "expr": "sum(rate(coredns_cache_hits_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", type=\"denial\",app_kubernetes_io_instance=\"node-local-dns\", zones=~\"sovcombank.*\"}[5m])) / sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\", zones=~\"sovcombank.*\"}[5m]))",
     "legendFormat": "hits: denial"
    },
    {
     "expr": "(sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\", zones=~\"sovcombank.*\"}[5m])) - sum(rate(coredns_cache_hits_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", type=\"success\", app_kubernetes_io_instance=\"node-local-dns\", zones=~\"sovcombank.*\"}[5m]))) / sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\", zones=~\"sovcombank.*\"}[5m]))",
     "legendFormat": "misses"
    },
    {
     "expr": "sum(rate(coredns_dnssec_cache_hits_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\", zones=~\"sovcombank.*\"}[5m])) / sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\", zones=~\"sovcombank.*\"}[5m]))",
     "legendFormat": "hits: DNSSEC"
    },
    {
     "expr": "(sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\",app_kubernetes_io_instance=\"node-local-dns\", zones=~\"sovcombank.*\"}[5m])) - sum(rate(coredns_dnssec_cache_hits_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\", zones=~\"sovcombank.*\"}[5m]))) / sum(rate(coredns_cache_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\", zones=~\"sovcombank.*\"}[5m]))",
     "legendFormat": "misses: DNSSEC"
    }
   ]
  },
  {
   "title": "Requests (by type)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{scb_k8s_name=~\"$cluster\", instance=~\"$instance\", app_kubernetes_io_instance=\"node-local-dns\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  { "title": "NodeLocalDNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Requests (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_requests_total{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "upstream"
    }
   ]
  },
  {
   "title": "Cache (hitrate)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_conn_cache_hits_total{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\"}[5m])) / sum(rate(coredns_forward_requests_total{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "(sum(rate(coredns_forward_requests_total{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\"}[5m])) - sum(rate(coredns_forward_conn_cache_hits_total{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\"}[5m]))) / sum(rate(coredns_forward_requests_total{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Requests (DNSSEC by zone)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_do_requests_total{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\"}[5m])) by (zone)",
     "legendFormat": "{{zone}}"
    }
   ]
  },
  {
   "title": "Responses (by code)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_responses_total{scb_k8s_name=~\"$cluster\", app_kubernetes_io_instance=\"node-local-dns\", instance=~\"$instance\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  }
 ]
}