{
 "title": "Kube-api-log",
 "tags": [ "kube-api" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {}
   },
   {
    "name": "verb",
    "label": "verb",
    "query": " get,list,update,path,post,delete,put,watch"
   },
   {
    "name": "responseStatus_code",
    "label": "responseStatus_code",
    "query": "200,201,400,403,404,410,500,504"
   }
  ]
 },
 "panels": [
  {
   "title": "Кол-во $responseStatus_code строк за среднию 1 минуту  ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (responseStatus_code) (count_over_time({k8s_clusters=~\"$cluster\"} | json | line_format \"{{.Line}}\" | verb=~\"$verb\" | responseStatus_code =~ \"$responseStatus_code\" [1m]))",
     "legendFormat": "{{ responseStatus_code }}"
    }
   ]
  },
  {
   "title": "Средние нагрузка  от какой SA к namespace с код ответа $responseStatus_code ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (objectRef_namespace, user_username) (rate({k8s_clusters=~\"$cluster\"} | json | line_format \"{{.Line}}\" | verb=~\"$verb\" | responseStatus_code =~ \"$responseStatus_code\" [1m]))",
     "legendFormat": "namespace: {{ objectRef_namespace }} | username: {{ user_username}} "
    }
   ]
  },
  {
   "title": "Resource request $verb status $responseStatus_code ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (objectRef_resource) (rate({k8s_clusters=~\"$cluster\"} | json | line_format \"{{.Line}}\" | verb=~\"$verb\" | responseStatus_code =~ \"$responseStatus_code\" [1m]))",
     "legendFormat": "{{ objectRef_resource }}"
    }
   ]
  },
  {
   "title": "Namespace Request $verb status $responseStatus_code ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (objectRef_namespace) (rate({k8s_clusters=~\"$cluster\"} | json | line_format \"{{.Line}}\" | verb=~\"$verb\" | responseStatus_code =~ \"$responseStatus_code\" [1m]))",
     "legendFormat": "{{ objectRef_namespace }}"
    }
   ]
  },
  {
   "title": "Средние нагрузка ресурса к методом $verb со кодом ответа $responseStatus_code ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (objectRef_namespace, objectRef_resource) (rate({k8s_clusters=~\"$cluster\"} | json | line_format \"{{.Line}}\" | verb=~\"$verb\" | responseStatus_code =~ \"$responseStatus_code\" [1m]))",
     "legendFormat": "namespace: {{ objectRef_namespace }} | resource: {{ objectRef_resource\t}} "
    }
   ]
  },
  {
   "title": "Средние нагрузка uri по $verb со кодом ответа $responseStatus_code ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (objectRef_namespace , requestURI) (rate({k8s_clusters=~\"$cluster\"} | json | line_format \"{{.Line}}\" | verb=~\"$verb\" | responseStatus_code =~ \"$responseStatus_code\" [1m]))",
     "legendFormat": "namespace: {{ objectRef_namespace }} | uri: {{ requestURI }} "
    }
   ]
  },
  {
   "title": "Средние нагрузка методом $verb  со кодом ответа $responseStatus_code по kube-api ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (job) (rate({k8s_clusters=~\"$cluster\"} | json | line_format \"{{.Line}}\" | verb=~\"$verb\" | responseStatus_code =~ \"$responseStatus_code\" [1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Запросы с фильтрацией по методу $verb и статусу $responseStatus_code",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "{k8s_clusters=~\"$cluster\"} | json | line_format \"{{.Line}}\" | verb=~\"$verb\" | responseStatus_code =~ \"$responseStatus_code\""
    }
   ]
  },
  { "title": "полный вывод лог", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Лог по get запросам",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "{k8s_clusters=~\"$cluster\"} | json | verb=~\"$verb\""
    }
   ]
  },
  {
   "title": "All logs",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "{k8s_clusters=~\"$cluster\"} |~ `update`"
    }
   ]
  }
 ]
}