apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: kill-container-process-by-id
spec:
  experiments:
    - scope: container
      target: process
      action: kill
      desc: "kill container process by id"
      matchers:
        - name: container-names
          value:
            - "productpage"
        - name: namespace
          value: ["bookinfo"]
        - name: process
          value: ["python"]
        - name: labels
          value: ["app=productpage"]