{
 "title": "Ingress NGINX Observability Overview",
 "description": "Overview of Ingress NGINX Controller deployed as a DaemonSet",
 "tags": [
  "kubernetes",
  "ingress",
  "nginx"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "scb_k8s_name", "label": "scb_k8s_name", "query": { "query": "label_values(scb_k8s_name)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{scb_k8s_name=\"$scb_k8s_name\"},namespace)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(nginx_ingress_controller_request_size_count{scb_k8s_name=\"$scb_k8s_name\", namespace=\"$namespace\"},host)"
    }
   },
   {
    "name": "path",
    "query": "label_values(nginx_ingress_controller_request_size_count{host=~\"$host\"}, path)"
   }
  ]
 },
 "panels": [
  { "title": "Traffic rps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOP 20 requests per minute (methos | uri)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(20, sum(increase(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[1m])) by(method, path))",
     "legendFormat": "{{path}} |  {{method}}"
    }
   ]
  },
  {
   "title": "requests per minute (method)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[1m])) by (method)",
     "legendFormat": "HTTP {{method}}"
    }
   ]
  },
  {
   "title": "requests per minute (ingress)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[1m])) by(host, path)",
     "legendFormat": "{{host}}{{path}} ({{instance}})"
    }
   ]
  },
  {
   "title": "requests per minute (status)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[1m])) by (status) > 0 ",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum{scb_k8s_name=\"$scb_k8s_name\"}[$__rate_interval]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum (irate (nginx_ingress_controller_response_size_sum{scb_k8s_name=\"$scb_k8s_name\"}[$__rate_interval]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "avg memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{scb_k8s_name=\"$scb_k8s_name\"})",
     "legendFormat": "memory |"
    }
   ]
  },
  {
   "title": "avg cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_cpu_seconds_total{scb_k8s_name=\"$scb_k8s_name\"}[$__rate_interval]))",
     "legendFormat": "cpu |"
    }
   ]
  },
  {
   "title": "Traffic in instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "requests per minute (ingress)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "rpm" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[1m])) by(instance, host, path)",
       "legendFormat": "{{host}}{{path}} ({{instance}})"
      }
     ]
    },
    {
     "title": "nginx  all connections/sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "conn/sec" } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_nginx_process_connections_total{scb_k8s_name=~\"$scb_k8s_name\"}[$__rate_interval])) by (state ,instance)",
       "legendFormat": "{{state}} | {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Certificate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingress Certificate Expiry",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{host=~\"$host\",scb_k8s_name=\"$scb_k8s_name\"}) by (host) - time()",
       "legendFormat": "{{ host }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Error 5xx | 4xx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "4xx requests per minute (method)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 13, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"4.*\", host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[1m])) by(status,method)",
       "legendFormat": "{{status}}  |  {{method}}"
      }
     ]
    },
    {
     "title": "5xx requests per minute (method)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 11, "x": 13, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.*\", host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[1m])) by(status,method)",
       "legendFormat": "{{status}}  |  {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "percentile response times & transfer rates",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(label_join(rate(nginx_ingress_controller_request_duration_seconds_bucket{host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[1m]), \"url\", \"\", \"host\", \"path\")) by (le, url)) > -1"
      },
      {
       "expr": "histogram_quantile(0.90, sum(label_join(rate(nginx_ingress_controller_request_duration_seconds_bucket{host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[1m]), \"url\", \"\", \"host\", \"path\")) by (le, url)) > -1"
      },
      {
       "expr": "histogram_quantile(0.99, sum(label_join(rate(nginx_ingress_controller_request_duration_seconds_bucket{host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[1m]), \"url\", \"\", \"host\", \"path\")) by (le, url)) > -1"
      },
      {
       "expr": "sum(label_join(irate(nginx_ingress_controller_request_size_sum{host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[$__rate_interval]), \"url\", \"\", \"host\", \"path\")) by (url)"
      },
      {
       "expr": "sum(label_join(irate(nginx_ingress_controller_response_size_sum{host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[$__rate_interval]), \"url\", \"\", \"host\", \"path\")) by (url)"
      }
     ]
    },
    {
     "title": "requests duration (2.5min buckets)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum by (le)(\r\n  increase(\r\n    nginx_ingress_controller_request_duration_seconds_bucket{\r\n      host =~ \"$host\",\r\n      path =~ \"$path\",\r\n      scb_k8s_name=\"$scb_k8s_name\"\r\n    }[150s]\r\n  )\r\n)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Срез path к latency по 99 перцентили  ",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99,   sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[$__rate_interval])) by (path, le) )",
       "legendFormat": "{{path}} |  p99"
      }
     ]
    },
    {
     "title": "Срез method к latency по 99 перцентили  ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99,   sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[$__rate_interval])) by (method, le) )",
       "legendFormat": "{{method}} |  p99"
      }
     ]
    },
    {
     "title": "Срез status code к latency по 99 перцентили  ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99,   sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{host=~\"$host\", path=~\"$path\", scb_k8s_name=\"$scb_k8s_name\"}[$__rate_interval])) by (status, le) )",
       "legendFormat": "{{status}} |  p99"
      }
     ]
    }
   ]
  }
 ]
}