---
apiVersion: v1
kind: ConfigMap
data:
  {{- range $key, $value := .Values.variables.ratings }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
metadata:
  name: ratings
  namespace: {{ .Values.namespace }}