apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: increase-container-cpu-load-by-id
spec:
  experiments:
    - scope: container
      target: cpu
      action: fullload
      desc: "increase container cpu load by id"
      matchers:
        - name: container-names
          value:
            - "productpage"
        - name: cpu-percent
          value: ["100"]
        - name: namespace
          value: ["bookinfo"]
        - name: labels
          value: ["app=productpage"] 
        - name: timeout
          value: ["360"]